### ISSUE TITLE
Docker: Cannot neighter Register nor Login - action buttons seem to do nothing 

### ISSUE THREAD

**Issue by CryptoNGuns** [itsalb3rt/cloudcsv#42]
**Describe the bug**

**To Reproduce**
1. Perform operation for installing APP
`$ git clone https://github.com/itsalb3rt/cloudcsv.git
$ docker-compose up`

2. Perform operation for installing API
`$ git clone https://github.com/itsalb3rt/cloudcsv_api.git
$ docker-compose up`

**Expected behavior**
Registration button works and redirect me to login or confirmation page
![bug](https://user-images.githubusercontent.com/46357919/191455561-3379d51d-1399-4ab5-9ec3-e4c514507937.png)

I also recorded my attempt of registration and wrong behaviour of button:
https://youtu.be/fjMj0Lc9stM

**Desktop (please complete the following information):**
 - OS: Tried on both: Centos and Linux Mint
 - Browser, Firefox, Chrome

**Comment by itsalb3rt** [comment]
Thanks for submitting the issue 🙌 I will check as soon as possible.

**Comment by CryptoNGuns** [comment]
Hello, thank you for fixing that issue. I confirm that now I can register and login. Best regards!
