### ISSUE TITLE
Use the email to create the username

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/cloudcsv#49]
**Is your feature request related to a problem? Please describe.**
Remove the username field from the login and register form and create the username from the email. Use the email to log in and keep the old behavior with the username into the login.

**Describe the solution you'd like**
Keep the column part of the user table, but don't force the user to create a username or remember this, after this implementation the mail is the key to login.

**Comment by rafieltq** [comment]
I want to take this issue, can you assign this to me?

**Comment by itsalb3rt** [comment]
Sure!
