### ISSUE TITLE
Read the body message on the register when the user already exists

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/cloudcsv#56]
**Is your feature request related to a problem? Please describe.**
Need to show to the user the parse message from the response.

**Describe the solution you'd like**

The server response with

> HTTP status 409
```json
{"message":"User Already Exist"}
```

On file `src/views/Auth/Register.vue` we need to read the `message` property and validate if this exists;

https://github.com/itsalb3rt/cloudcsv/blob/a81e0b969afc70013e8fac0a1e893c4d9d0f164e/src/views/Auth/Register.vue#L140

You can do any like that;

```javascript

const message = error.response.data && error.response.data.message ? error.response.data.message : 'We have an error, please try again in a few moment.';
this.$store.commit("snackbar/setSnackbar", {
 show: true,
 message: message,
 color: "error",
 top: true
});
```

**Describe alternatives you've considered**
None

**Comment by franciscoemanuel** [comment]
@itsalb3rt Working on it

**Comment by itsalb3rt** [comment]
sure @franciscoemanuel 🙌
